### ISSUE TITLE
[HOT-FIX] - AndroidJavaException: java.lang.NoSuchFieldError: no field "SUPRESS"

### ISSUE THREAD

**Issue by alkanyunus** [adjust/unity_sdk#316]
Hello,

**_Adjust v5.0.4 installed via UPM_**

I think a hot-fix should be released asap because of log level issue on Unity wrapper. When you use suppress log level, android throws run time exception:

`
AndroidJavaException: java.lang.NoSuchFieldError: no "Ljava/lang/Object;" field "SUPRESS" in class "Lcom/adjust/sdk/LogLevel;" or its superclasses
                                                                                                    java.lang.NoSuchFieldError: no "Ljava/lang/Object;" field "SUPRESS" in class "Lcom/adjust/sdk/LogLevel;" or its superclasses
                                                                                                    	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                                                    	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
                                                                                                    	at com.unity3d.player.B0.handleMessage(Unknown Source:122)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at com.unity3d.player.C0.run(Unknown Source:24)
                                                                                                      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
                                                                                                      at UnityEngine.AndroidJNISafe.GetStaticFieldID (System.IntPtr clazz, System.String name, System.String sig) [0x00000] in <00000000000000000000000000000000>:0 
                                                                                                      at UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName,`

https://github.com/adjust/unity_sdk/blob/a5009aac5c90f20c7f374c937f20539b11794dac/Assets/Adjust/Scripts/AdjustAndroid.cs#L60

"SUPRESS" should be replaced with "**SUPPRESS**".

**Comment by uerceg** [comment]
Hello @alkanyunus,

Thanks for the report and nice catch. We'll address this in 5.0.5 patch update. I will keep you posted.

**Comment by uerceg** [comment]
Hello @alkanyunus,

If you can give [v5.0.5](https://github.com/adjust/unity_sdk/releases/tag/v5.0.5) a shot to check if issue might have been resolved with it, that'd be great.

Looking forward to hearing back from you.

**Comment by alkanyunus** [comment]
> Hello @alkanyunus,
> 
> If you can give [v5.0.5](https://github.com/adjust/unity_sdk/releases/tag/v5.0.5) a shot to check if issue might have been resolved with it, that'd be great.
> 
> Looking forward to hearing back from you.

Yes, it is working now. Thanks for the quick release 👍

**Comment by uerceg** [comment]
Great, thank you for the confirmation and reporting this. Cheers.
